### PR TITLE
Get all iTXt chunks

### PR DESCRIPTION
**Pull request by briancullen**
Not sure if you are still maintaining this but I recently needed a library to read text from a PNG file and your library fitted the bill. One of the changes I made was to allow you to request all the iTXt chunks which I saw you have marked as an issue. Syntax for the command is as follows (basically leave out the keyword).

``` js
fs.createReadStream('output.png')
  .pipe(pngitxt.get(function (key, value) {
    console.log(key, ":", value)
  }))
```

I left it so that a null keyword should still return nothing so that the behaviour from before is unchanged. An exception is thrown if no callback function is found. Can't figure out why you would try and call this library without a callback.

### CODE REVIEW

**Comment by finnp** [comment]
Great, good job! :+1:  I added you as a collaborator in case you want to continue working on it or fix bugs.

**Comment by briancullen** [comment]
Thanks for accepting the pull request and for adding me.

I am still playing with the code on a separate branch where I am making a few changes for things I needed or wanted. In particular I changed it to read all the different types text chunks in a PNG and to allow regular expressions for matching the keywords. Do you want me to keep pushing changes when I'm happy with them or would you like to check them first?

**Comment by finnp** [comment]
Feel free to push to the master branch with changes! If you want to publish a new version to npm, let me know and then I'll might review the changes.

**Comment by briancullen** [comment]
Hello again.

Have to admit I may have taken the development of the tool a bit further than I initially indicated but I hadn't used some of the technologies before and I was experimenting. Anyway I think I have just about pushed it as far as I'm going to for now. If you think that what is currently in the master branch is worth an npm release then it would be great to see it - would definitely be a version 2.0.0 as the API has changed. 

Either way would be interested in your views on what functionality is useful,

Brian.

**Pull request merged**
